"""UVM Environment Generator - Generates complete UVM verification environments."""

from ..rtl_parser.parser import DesignModule


class UVMGenerator:
    """Generates complete UVM environments for RTL modules.

    Generates:
    - Sequence Items
    - Sequences (base, directed, random)
    - Driver
    - Monitor
    - Scoreboard
    - Agent
    - Environment
    - Test base class
    - Test examples
    """

    def generate(self, modules: list[DesignModule]) -> list[dict]:
        """Generate UVM environment for all modules."""
        uvm_components = []
        for module in modules:
            uvm_components.extend(self._gen_uvm_environment(module))
        return uvm_components

    def _gen_uvm_environment(self, module: DesignModule) -> list[dict]:
        """Generate complete UVM environment for a single module."""
        components = []

        # 1. Sequence Item
        components.append(self._gen_sequence_item(module))

        # 2. Sequences
        components.extend(self._gen_sequences(module))

        # 3. Interface
        components.append(self._gen_interface(module))

        # 4. Driver
        components.append(self._gen_driver(module))

        # 5. Monitor
        components.append(self._gen_monitor(module))

        # 6. Scoreboard
        components.append(self._gen_scoreboard(module))

        # 7. Agent
        components.append(self._gen_agent(module))

        # 8. Environment
        components.append(self._gen_environment(module))

        # 9. Base Test
        components.append(self._gen_base_test(module))

        # 10. Example Tests
        components.extend(self._gen_example_tests(module))

        return components

    def _gen_sequence_item(self, module: DesignModule) -> dict:
        """Generate UVM sequence item."""
        code = f"""// UVM Sequence Item for {module.name}
// Generated by VerifiX AI UVM Generator

class {module.name}_seq_item extends uvm_sequence_item;
  `uvm_object_utils({module.name}_seq_item)

"""

        for port in module.ports:
            width_val = self._parse_width(port.width)
            direction = "rand" if port.direction.value in ("input", "inout") else ""
            code += f"  {direction} logic [{width_val}:0] {port.name};\n"

        code += f"""
  function new(string name = "{module.name}_seq_item");
    super.new(name);
  endfunction

  function string convert2string();
    return $sformatf("{module.name}_seq_item: """
        for i, port in enumerate(module.ports[:4]):
            code += f"{port.name}=%h "
        code += f""");
  endfunction

  function void do_copy(uvm_object rhs);
    {module.name}_seq_item rhs_;
    $cast(rhs_, rhs);
    super.do_copy(rhs);
"""
        for port in module.ports:
            code += f"    {port.name} = rhs_.{port.name};\n"
        code += f"""  endfunction

  function bit do_compare(uvm_object rhs, uvm_comparer comparer);
    {module.name}_seq_item rhs_;
    $cast(rhs_, rhs);
    return super.do_compare(rhs, comparer);
  endfunction

endclass
"""
        return {
            "name": f"{module.name}_seq_item",
            "component_type": "sequence_item",
            "code": code,
            "description": f"UVM sequence item for {module.name} transaction representation",
        }

    def _gen_sequences(self, module: DesignModule) -> list[dict]:
        """Generate UVM sequences."""
        sequences = []

        # Base sequence
        code = f"""// UVM Base Sequence for {module.name}
// Generated by VerifiX AI UVM Generator

class {module.name}_base_seq extends uvm_sequence #({module.name}_seq_item);
  `uvm_object_utils({module.name}_base_seq)

  function new(string name = "{module.name}_base_seq");
    super.new(name);
  endfunction

  virtual task body();
    {module.name}_seq_item item;
    repeat(100) begin
      item = {module.name}_seq_item::type_id::create("item");
      start_item(item);
      assert(item.randomize());
      finish_item(item);
    end
  endtask

endclass
"""
        sequences.append({
            "name": f"{module.name}_base_seq",
            "component_type": "sequence",
            "code": code,
            "description": f"Base UVM sequence for {module.name} random stimulus",
        })

        # Directed sequence
        code = f"""// UVM Directed Sequence for {module.name}
// Generated by VerifiX AI UVM Generator

class {module.name}_directed_seq extends uvm_sequence #({module.name}_seq_item);
  `uvm_object_utils({module.name}_directed_seq)

  function new(string name = "{module.name}_directed_seq");
    super.new(name);
  endfunction

  virtual task body();
    {module.name}_seq_item item;

    // Reset scenario
    item = {module.name}_seq_item::type_id::create("reset_item");
    start_item(item);
    assert(item.randomize() with {{
"""
        for port in module.input_ports[:3]:
            code += f"      {port.name} == 0;\n"
        code += f"""    }});
    finish_item(item);

    // Normal operation
    repeat(20) begin
      item = {module.name}_seq_item::type_id::create("normal_item");
      start_item(item);
      assert(item.randomize());
      finish_item(item);
    end

    // Back-to-back transfers
    repeat(10) begin
      item = {module.name}_seq_item::type_id::create("btb_item");
      start_item(item);
      assert(item.randomize());
      finish_item(item);
    end
  endtask

endclass
"""
        sequences.append({
            "name": f"{module.name}_directed_seq",
            "component_type": "sequence",
            "code": code,
            "description": f"Directed UVM sequence for {module.name} targeted scenarios",
        })

        return sequences

    def _gen_interface(self, module: DesignModule) -> dict:
        """Generate SystemVerilog interface."""
        clk = module.clock_signals[0] if module.clock_signals else "clk"
        rst = module.reset_signals[0] if module.reset_signals else "rst"

        code = f"""// SystemVerilog Interface for {module.name}
// Generated by VerifiX AI UVM Generator

interface {module.name}_if (input logic {clk}, input logic {rst});
"""
        for port in module.ports:
            width_val = self._parse_width(port.width)
            direction = "input" if port.direction.value == "input" else "output" if port.direction.value == "output" else "inout"
            code += f"  {direction} logic [{width_val}:0] {port.name};\n"
        code += f"""
  // Clocking block for driver
  clocking cb_drv @(posedge {clk});
    default input #1 output #1;
"""
        for port in module.input_ports:
            code += f"    output {port.name};\n"
        for port in module.output_ports:
            code += f"    input {port.name};\n"
        code += f"""  endclocking

  // Clocking block for monitor
  clocking cb_mon @(posedge {clk});
    default input #1 output #1;
"""
        for port in module.ports:
            code += f"    input {port.name};\n"
        code += f"""  endclocking

  // Modport for driver
  modport DRV (clocking cb_drv, input {clk}, input {rst});

  // Modport for monitor
  modport MON (clocking cb_mon, input {clk}, input {rst});

  // Modport for DUT
  modport DUT (
"""
        for port in module.ports:
            direction = port.direction.value
            code += f"    {direction} {port.name},\n"
        code += f"    input {clk},\n"
        code += f"    input {rst}\n"
        code += f"""  );

endinterface
"""
        return {
            "name": f"{module.name}_if",
            "component_type": "interface",
            "code": code,
            "description": f"SystemVerilog interface for {module.name} with clocking blocks",
        }

    def _gen_driver(self, module: DesignModule) -> dict:
        """Generate UVM driver."""
        code = f"""// UVM Driver for {module.name}
// Generated by VerifiX AI UVM Generator

class {module.name}_driver extends uvm_driver #({module.name}_seq_item);
  `uvm_component_utils({module.name}_driver)

  virtual {module.name}_if vif;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db #(virtual {module.name}_if)::get(this, "", "vif", vif)) begin
      `uvm_fatal("NOVIF", "Virtual interface not found for {module.name}_driver")
    end
  endfunction

  virtual task run_phase(uvm_phase phase);
    {module.name}_seq_item item;
    forever begin
      seq_item_port.get_next_item(item);
      drive_item(item);
      seq_item_port.item_done();
    end
  endtask

  virtual task drive_item({module.name}_seq_item item);
    @(vif.cb_drv);
"""
        for port in module.input_ports:
            code += f"    vif.cb_drv.{port.name} <= item.{port.name};\n"
        code += f"""  endtask

endclass
"""
        return {
            "name": f"{module.name}_driver",
            "component_type": "driver",
            "code": code,
            "description": f"UVM driver for {module.name} stimulus driving",
        }

    def _gen_monitor(self, module: DesignModule) -> dict:
        """Generate UVM monitor."""
        clk = module.clock_signals[0] if module.clock_signals else "clk"
        code = f"""// UVM Monitor for {module.name}
// Generated by VerifiX AI UVM Generator

class {module.name}_monitor extends uvm_monitor;
  `uvm_component_utils({module.name}_monitor)

  uvm_analysis_port #({module.name}_seq_item) ap;
  virtual {module.name}_if vif;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    ap = new("ap", this);
    if (!uvm_config_db #(virtual {module.name}_if)::get(this, "", "vif", vif)) begin
      `uvm_fatal("NOVIF", "Virtual interface not found for {module.name}_monitor")
    end
  endfunction

  virtual task run_phase(uvm_phase phase);
    {module.name}_seq_item item;
    forever begin
      @(vif.cb_mon);
      item = {module.name}_seq_item::type_id::create("item");
"""
        for port in module.ports:
            code += f"      item.{port.name} = vif.cb_mon.{port.name};\n"
        code += f"""      ap.write(item);
    end
  endtask

endclass
"""
        return {
            "name": f"{module.name}_monitor",
            "component_type": "monitor",
            "code": code,
            "description": f"UVM monitor for {module.name} signal observation",
        }

    def _gen_scoreboard(self, module: DesignModule) -> dict:
        """Generate UVM scoreboard."""
        code = f"""// UVM Scoreboard for {module.name}
// Generated by VerifiX AI UVM Generator

class {module.name}_scoreboard extends uvm_scoreboard;
  `uvm_component_utils({module.name}_scoreboard)

  uvm_analysis_imp #({module.name}_seq_item, {module.name}_scoreboard) ap;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    ap = new("ap", this);
  endfunction

  virtual function void write({module.name}_seq_item item);
    // TODO: Implement reference model and comparison logic
    `uvm_info("SB_WRITE", $sformatf("Received: %s", item.convert2string()), UVM_MEDIUM)
  endfunction

endclass
"""
        return {
            "name": f"{module.name}_scoreboard",
            "component_type": "scoreboard",
            "code": code,
            "description": f"UVM scoreboard for {module.name} functional checking",
        }

    def _gen_agent(self, module: DesignModule) -> dict:
        """Generate UVM agent."""
        code = f"""// UVM Agent for {module.name}
// Generated by VerifiX AI UVM Generator

class {module.name}_agent extends uvm_agent;
  `uvm_component_utils({module.name}_agent)

  {module.name}_driver drv;
  {module.name}_monitor mon;
  {module.name}_sequencer sqr;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (is_active == UVM_ACTIVE) begin
      drv = {module.name}_driver::type_id::create("drv", this);
      sqr = {module.name}_sequencer::type_id::create("sqr", this);
    end
    mon = {module.name}_monitor::type_id::create("mon", this);
  endfunction

  virtual function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    if (is_active == UVM_ACTIVE) begin
      drv.seq_item_port.connect(sqr.seq_item_export);
    end
  endfunction

endclass
"""
        return {
            "name": f"{module.name}_agent",
            "component_type": "agent",
            "code": code,
            "description": f"UVM agent for {module.name} containing driver/monitor/sequencer",
        }

    def _gen_environment(self, module: DesignModule) -> dict:
        """Generate UVM environment."""
        code = f"""// UVM Environment for {module.name}
// Generated by VerifiX AI UVM Generator

class {module.name}_env extends uvm_env;
  `uvm_component_utils({module.name}_env)

  {module.name}_agent agt;
  {module.name}_scoreboard sb;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    agt = {module.name}_agent::type_id::create("agt", this);
    sb = {module.name}_scoreboard::type_id::create("sb", this);
  endfunction

  virtual function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    agt.mon.ap.connect(sb.ap);
  endfunction

endclass
"""
        return {
            "name": f"{module.name}_env",
            "component_type": "environment",
            "code": code,
            "description": f"UVM environment for {module.name} integrating agent and scoreboard",
        }

    def _gen_base_test(self, module: DesignModule) -> dict:
        """Generate UVM base test."""
        code = f"""// UVM Base Test for {module.name}
// Generated by VerifiX AI UVM Generator

class {module.name}_base_test extends uvm_test;
  `uvm_component_utils({module.name}_base_test)

  {module.name}_env env;
  {module.name}_base_seq base_seq;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    env = {module.name}_env::type_id::create("env", this);
    base_seq = {module.name}_base_seq::type_id::create("base_seq");
  endfunction

  virtual task run_phase(uvm_phase phase);
    phase.raise_objection(this);
    base_seq.start(env.agt.sqr);
    phase.drop_objection(this);
  endtask

endclass
"""
        return {
            "name": f"{module.name}_base_test",
            "component_type": "test",
            "code": code,
            "description": f"UVM base test for {module.name} running base sequence",
        }

    def _gen_example_tests(self, module: DesignModule) -> list[dict]:
        """Generate example UVM tests."""
        tests = []

        # Directed test
        code = f"""// UVM Directed Test for {module.name}
// Generated by VerifiX AI UVM Generator

class {module.name}_directed_test extends {module.name}_base_test;
  `uvm_component_utils({module.name}_directed_test)

  {module.name}_directed_seq directed_seq;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    directed_seq = {module.name}_directed_seq::type_id::create("directed_seq");
  endfunction

  virtual task run_phase(uvm_phase phase);
    phase.raise_objection(this);
    directed_seq.start(env.agt.sqr);
    phase.drop_objection(this);
  endtask

endclass
"""
        tests.append({
            "name": f"{module.name}_directed_test",
            "component_type": "test",
            "code": code,
            "description": f"UVM directed test for {module.name}",
        })

        # Random test
        code = f"""// UVM Random Test for {module.name}
// Generated by VerifiX AI UVM Generator

class {module.name}_random_test extends {module.name}_base_test;
  `uvm_component_utils({module.name}_random_test)

  {module.name}_base_seq random_seq;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    random_seq = {module.name}_base_seq::type_id::create("random_seq");
  endfunction

  virtual task run_phase(uvm_phase phase);
    phase.raise_objection(this);
    repeat(5) begin
      random_seq.start(env.agt.sqr);
    end
    phase.drop_objection(this);
  endtask

endclass
"""
        tests.append({
            "name": f"{module.name}_random_test",
            "component_type": "test",
            "code": code,
            "description": f"UVM random test for {module.name}",
        })

        # Reset test
        code = f"""// UVM Reset Test for {module.name}
// Generated by VerifiX AI UVM Generator

class {module.name}_reset_test extends {module.name}_base_test;
  `uvm_component_utils({module.name}_reset_test)

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual task run_phase(uvm_phase phase);
    {module.name}_seq_item item;
    phase.raise_objection(this);

    // Apply reset
    item = {module.name}_seq_item::type_id::create("reset_item");
    item.randomize() with {{
"""
        for port in module.input_ports[:3]:
            code += f"      {port.name} == 0;\n"
        code += f"""    }};
    item.start(env.agt.sqr);
    #200ns;

    // Release reset and run random
    repeat(20) begin
      item = {module.name}_seq_item::type_id::create("item");
      item.randomize();
      item.start(env.agt.sqr);
    end

    phase.drop_objection(this);
  endtask

endclass
"""
        tests.append({
            "name": f"{module.name}_reset_test",
            "component_type": "test",
            "code": code,
            "description": f"UVM reset test for {module.name}",
        })

        return tests

    def _parse_width(self, width_str: str) -> str:
        """Parse width string and return bit width."""
        if not width_str:
            return "0"
        import re
        match = re.match(r"\[(\d+):(\d+)\]", width_str)
        if match:
            msb = int(match.group(1))
            lsb = int(match.group(2))
            return str(msb - lsb)
        return "0"